-- CAU 1 TAO DATABASE
CREATE DATABASE BAITHI2
GO
USE BAITHI2
GO
--
CREATE TABLE HLV
(
MAHLV varchar(10) not null,
TENHLV varchar(40) ,
QUOCTICH varchar(20),
NGSINH  smalldatetime,
)

CREATE TABLE DOITUYEN
(
MADT varchar(10) NOT NULL,
MAHLV VARCHAR(10),
QUOCGIA VARCHAR(20),
CHAULUC VARCHAR (10),
DIEM INT,
)

CREATE TABLE FINALWC
(
MAFWC VARCHAR(10) NOT NULL,
NUOCTC VARCHAR (20),
NAM INT,
NGBD SMALLDATETIME,
TONGKP MONEY,
)
 
 CREATE TABLE KETQUA
 (
 MAKQ VARCHAR(10) NOT NULL ,
 MADT VARCHAR(10),
 MAFWC VARCHAR(10),
 TONGSOBT INT ,
 THUHANG INT,
 HUYCHUONG VARCHAR(10),
 )

ALTER TABLE HLV ADD CONSTRAINT pk_hlv PRIMARY KEY (MAHLV)
ALTER TABLE DOITUYEN ADD CONSTRAINT pk_doituyen PRIMARY KEY (MADT)
ALTER TABLE FINALWC ADD CONSTRAINT pk_fwc PRIMARY KEY (MAFWC)
ALTER TABLE KETQUA ADD CONSTRAINT pk_kq PRIMARY KEY (MAKQ)

ALTER TABLE DOITUYEN ADD FOREIGN KEY (MAHLV) REFERENCES HLV(MAHLV)
ALTER TABLE KETQUA ADD FOREIGN KEY (MADT) REFERENCES DOITUYEN(MADT)
ALTER TABLE KETQUA ADD FOREIGN KEY (MAFWC) REFERENCES FINALWC(MAFWC)

-- CAU 2
INSERT INTO HLV VALUES ('HLV001', 'Adenor Leonardo Bacchi', 'Brazil',' 1961/05/25')
INSERT INTO HLV VALUES ('HLV002', 'Hansi Flick', 'Duc',' 1965/02/24')
INSERT INTO HLV VALUES ('HLV003', 'Roberto Martinez', 'Tay Ban Nha',' 1973/07/13')
select * from HLV

INSERT INTO DOITUYEN VALUES ('DT001','HLV001', 'Brazil','Chau My' ,' 243')
INSERT INTO DOITUYEN VALUES ('DT002','HLV002', 'Duc','Chau Au' ,'222')
INSERT INTO DOITUYEN VALUES ('DT003','HLV003', 'Bi','Chau Au' ,'72')
select * from DOITUYEN

INSERT INTO FINALWC VALUES ('WC001','Quatar','2022','2022/11/20' ,'13')
INSERT INTO FINALWC VALUES ('WC002','Nga','2018','2018/06/14' ,'8')
INSERT INTO FINALWC VALUES ('WC003','Brazil','2014','2014/06/12' ,'7')
select * from FINALWC

INSERT INTO KETQUA VALUES ('KQ001','DT001','WC001','10','1' ,'Vang')
INSERT INTO KETQUA VALUES ('KQ002','DT002','WC001','9','3' ,'Bac')
INSERT INTO KETQUA VALUES ('KQ003','DT003','WC001','3','10' ,NULL)
select * from KETQUA
-- CAU 3

-- CAU 4 
--CAU 5
SELECT HLV.MAHLV, TENHLV FROM HLV JOIN DOITUYEN DT
ON DT.MAHLV = HLV.MAHLV
WHERE DT.QUOCGIA = HLV.QUOCTICH
--CAU 6

--CAU 7
--CAU 8