-- CAU 1
CREATE DATABASE QLPT
GO

USE QLPT

GO

CREATE TABLE  PHONGTRO
(
MaPT char(5) not null,
TenPT nvarchar(50),
DienTich float,
LoaiPT nvarchar(15),
GiaPT money,
TinhTrangPT  nvarchar(20),
)


CREATE TABLE  CUDAN
(
MaCD char(5) not null,
HoTen nvarchar(50),
CCCD  nvarchar(12),
DiaChi nvarchar(100),
SoDT  varchar(15),
TrangThaiCD  nvarchar(15),
)

CREATE TABLE HOPDONG
(
MaHD char(5) not null,
MaCD char(5),
MaPT char(5),
NgayKy smalldatetime,
NgayHetHan smalldatetime,
TrangThaiHD nvarchar(20),
)
CREATE TABLE DICHVU
(
MaDV char(5) not null,
TenDV nvarchar(50),
DonGia money,
)

CREATE TABLE PHIEUTINHTIEN
(
MaPTT char(5) not null,
MaHD char(5),
SoTienDichVu money,
SoTienThuePT money,
TongTienTT money,
NgayTinhTien smalldatetime,
TinhTrangTT nvarchar(20),
PhuongThucTT nvarchar(20),
)

CREATE TABLE CHITIETTTDV
(
MaPTT char(5) not null ,
MaDV char(5)  not null,
ChiSoDV float,
ThanhTien money,
)

ALTER TABLE PHONGTRO ADD CONSTRAINT pk_pt PRIMARY KEY (MaPT)
ALTER TABLE  CUDAN ADD CONSTRAINT pk_cd PRIMARY KEY (MaCD)
ALTER TABLE   HOPDONG ADD CONSTRAINT pk_hd PRIMARY KEY (MaHD)
ALTER TABLE   DICHVU ADD CONSTRAINT pk_dv PRIMARY KEY (MaDV)
ALTER TABLE PHIEUTINHTIEN   ADD CONSTRAINT pk_ptt PRIMARY KEY (MaPTT )
ALTER TABLE CHITIETTTDV   ADD CONSTRAINT pk_ctdv PRIMARY KEY (MaPTT,MaDV )


ALTER TABLE HOPDONG ADD FOREIGN KEY (MaCD) REFERENCES  CUDAN(MaCD)
ALTER TABLE HOPDONG ADD FOREIGN KEY (MaPT) REFERENCES  PHONGTRO(MaPT)

ALTER TABLE PHIEUTINHTIEN ADD FOREIGN KEY (MaHD) REFERENCES  HOPDONG(MaHD)

ALTER TABLE  CHITIETTTDV ADD FOREIGN KEY (MaPTT) REFERENCES  PHIEUTINHTIEN(MaPTT)
ALTER TABLE CHITIETTTDV ADD FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
GO
--CAU 2
 --2.1
 ALTER TABLE DICHVU ADD CONSTRAINT CK_GIA CHECK (DonGia >= 2000 and DonGia <= 500000)
 GO
 --2.2
 ALTER TABLE PHONGTRO ADD CONSTRAINT CK_LPT CHECK ( LoaiPT in ('Kiot' , 'Co gac xep','Khong gac xep') )
 --2.3
 GO

 --CAU 3 
 --3.1
 SELECT PTT.MaPTT, MaHD, ChiSoDV,ThanhTien from PHIEUTINHTIEN PTT JOIN CHITIETTTDV CT
 ON PTT.MaPTT=CT.MaPTT join DICHVU DV on CT.MaDV= DV.MaDV
 WHERE YEAR(NgayTinhTien) =2024 AND DV.TenDV ='Dien'
 GO
 --3.2
 SELECT PT.MaPT, TenPT FROM PHONGTRO PT JOIN HOPDONG HD
 ON HD.MaPT= PT.MaPT JOIN PHIEUTINHTIEN PTT ON PTT.MaHD= HD.MaHD
 WHERE YEAR( HD.NgayKy)= 2024 and PT.LoaiPT='Khong gac xep' 
 and PTT.PhuongThucTT ='Chuyen khoan' and PTT.TongTienTT < 4000000
 --3.3
 GO
 SELECT MaCD, HoTen FROM CUDAN 
 WHERE NOT EXISTS ( SELECT * FROM  PHONGTRO WHERE LoaiPT = 'Kiot' AND DienTich='40'
	GO											and not exists ( SELECT * FROM HOPDONG HD WHERE HD.MaCD= CUDAN.MaCD AND HD.MaPT =PHONGTRO.MaPT))
--3.4
SELECT CD.MaCD, HoTen, COUNT(MaHD) AS SOLUONGHOPDONG FROM CUDAN CD JOIN HOPDONG HD ON HD.MaCD= CD.MaCD
WHERE YEAR( NgayKy) =2022
GROUP BY CD.MaCD, HoTen
GO
--3.5
SElECT TOP 1 HD.MaHD FROM HOPDONG HD JOIN PHIEUTINHTIEN PTT ON HD.MaHD =PTT.MaHD JOIN CHITIETTTDV CT 
ON CT.MaPTT=PTT.MaPTT JOIN DICHVU DV ON DV.MaDV = CT.MaDV
WHERE DV.TenDV ='Dien'
GROUP BY HD.MaHD
ORDER BY SUM(CT.ChiSoDV) DESC
GO